### ISSUE TITLE
Configuration Issue vccapikey - kubernetes manifest

### ISSUE THREAD

**Issue by hasselrot** [Dielee/volvo2mqtt#113]
**Describe the bug**
Hi!

Im trying to run volvo2mqtt in my kubernetes environment.
But running into configuration issues with the ENV Variables.

```
% kubectl logs volvo-deployment-65755cc76-kv6t6 -n home
Oct 21 21:08:21 volvo2mqtt [1] - INFO: Starting volvo2mqtt version v1.8.8
Traceback (most recent call last):
  File "/volvoAAOS2mqtt/./main.py", line 11, in <module>
    validate_settings()
  File "/volvoAAOS2mqtt/util.py", line 147, in validate_settings
    setting_keys = settings.volvoData["vccapikey"]
TypeError: string indices must be integers
```

Im sure it is something with the vccapikey that I am misunderstanding. I have added the primary and secondary keys that I created on the volvo developer page.

**To Reproduce**:<br>
My kubernetes configuration here, with bogus vccapikeys.

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: volvo-deployment
  namespace: home
spec:
  replicas: 1
  selector:
    matchLabels:
      app: volvo
  template:
    metadata:
      name: volvo
      namespace: home
      labels:
        app: volvo
    spec:
      containers:
      - name: volvo-container
        image: ghcr.io/dielee/volvo2mqtt:latest
        imagePullPolicy: Always
        env:
        - name: CONF_updateInterval
          value: "300"
        - name: CONF_babelLocale
          value: "sv_SE"
        - name: CONF_mqtt
          value: '{"broker": "10.3.0.51", "username": "", "password": "", "port": 8182}'
        - name: CONF_volvoData
          value: '{"username": "EMAILHERE", "password": "PASSWORDHERE", "vin": "VINHERE", "vccapikey": ["f9112312364666162f","ab31234bebe3234"], "odometerMultiplier": 1, "averageSpeedDivider": 1, "averageFuelConsumptionMultiplier": 1}'
        - name: TZ
          value: "Europe/Berlin"
```

Would very much appreciate any help!
Thanks!
